package vista;

import Modelo.Clientes.Cliente;
import Modelo.Producto.Productos;
import Modelo.Proveedores.Proveedor;
import clases.Ventas;
import clases.Pluses;
import clases.PlusesColab;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Crisp
 */
public class MenuTiendaView extends javax.swing.JFrame {

    //Creación de todos los ArrayList para luego ser llamados.
    ArrayList<Productos> listaC = new ArrayList();
    ArrayList<Pluses> listaPluses = new ArrayList();
    ArrayList<Proveedor> listaPuestos = new ArrayList();
    ArrayList<PlusesColab> listaPColab = new ArrayList();
    ArrayList<Ventas> listaPlanilla = new ArrayList();
    ArrayList<Cliente> listaCliente = new ArrayList();

    /**
     * Creates new form PaniSys
     */
    public MenuTiendaView() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGestionColab = new javax.swing.JButton();
        btnPlanillas = new javax.swing.JButton();
        btnGetionProveedorSIBD = new javax.swing.JButton();
        btnBD = new javax.swing.JButton();
        mnuMenuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gestión de Plantillas ");
        setIconImage(getIconImage());

        btnGestionColab.setText("Gestión de Productos");
        btnGestionColab.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnGestionColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionColabActionPerformed(evt);
            }
        });

        btnPlanillas.setText("Planillas");
        btnPlanillas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnPlanillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanillasActionPerformed(evt);
            }
        });

        btnGetionProveedorSIBD.setText("pruebaproveedor si bd");
        btnGetionProveedorSIBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetionProveedorSIBDActionPerformed(evt);
            }
        });

        btnBD.setText("ClientesBD");
        btnBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBDActionPerformed(evt);
            }
        });
        setJMenuBar(mnuMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGestionColab, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPlanillas, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(btnGetionProveedorSIBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestionColab, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlanillas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGetionProveedorSIBD, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(btnBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionColabActionPerformed
        ProductosView winColaborador = new ProductosView(this, false);
        winColaborador.setVisible(true);
    }//GEN-LAST:event_btnGestionColabActionPerformed

    private void btnPlanillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanillasActionPerformed
//        VentasView winPlanilla = new VentasView(this, false, listaPlanilla, listaCliente, listaPuestos, listaPColab, listaPluses, listaC);
//        winPlanilla.setVisible(true);
//        //Lo que hace es que los datos del JDialog los devuelve 
//        this.listaPlanilla = winPlanilla.listaPlanilla;
    }//GEN-LAST:event_btnPlanillasActionPerformed

    private void btnGetionProveedorSIBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetionProveedorSIBDActionPerformed
        ProveedorView view = new ProveedorView(null, true);
        view.setVisible(true);

    }//GEN-LAST:event_btnGetionProveedorSIBDActionPerformed

    private void btnBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBDActionPerformed
        ClientesView view = new ClientesView(null, true);
        view.setVisible(true);
    }//GEN-LAST:event_btnBDActionPerformed
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource(
                        "img/recurso.png"));
        return retValue;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTiendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTiendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTiendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTiendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTiendaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBD;
    private javax.swing.JButton btnGestionColab;
    private javax.swing.JButton btnGetionProveedorSIBD;
    private javax.swing.JButton btnPlanillas;
    private javax.swing.JMenuBar mnuMenuBar;
    // End of variables declaration//GEN-END:variables
}
