package vista;

import Modelo.Clientes.Cliente;
import clases.Productos;
import clases.Ventas;
import clases.Pluses;
import clases.PlusesColab;
import clases.Proveedor;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import vista.Cliente.FrmCliente;
import vista.Proveedor.FrmProveedor;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Crisp
 */
public class PaniSys extends javax.swing.JFrame {

    //Creación de todos los ArrayList para luego ser llamados.
    ArrayList<Productos> listaC = new ArrayList();
    ArrayList<Pluses> listaPluses = new ArrayList();
    ArrayList<Proveedor> listaPuestos = new ArrayList();
    ArrayList<PlusesColab> listaPColab = new ArrayList();
    ArrayList<Ventas> listaPlanilla = new ArrayList();
    ArrayList<Cliente> listaCliente = new ArrayList();

    /**
     * Creates new form PaniSys
     */
    public PaniSys() {
        initComponents();
        setLocationRelativeTo(null);

        // Crear menú
        JMenuBar menuBar = new JMenuBar();
        JMenu menuJuego = new JMenu("Gestión de Colaboradores");
        JMenuItem itemIniciar = new JMenuItem("Gestión de Pluses");
        JMenuItem itemAbortar = new JMenuItem("Gestión de Puestos");
        JMenuItem itemUltimoGanador = new JMenuItem("Asignar Pluses");
        JMenuItem itemAcercaDe = new JMenuItem("Planillas");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGestionProveedoresNOBD = new javax.swing.JButton();
        btnGestionColab = new javax.swing.JButton();
        btnPlanillas = new javax.swing.JButton();
        btnGetionProveedorSIBD = new javax.swing.JButton();
        btnBD = new javax.swing.JButton();
        mnuMenuBar = new javax.swing.JMenuBar();
        mnuMenu = new javax.swing.JMenu();
        mnuItemGesColab = new javax.swing.JMenuItem();
        mnuItemGesPuestos = new javax.swing.JMenuItem();
        mnuPlanilla = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gestión de Plantillas ");
        setIconImage(getIconImage());

        btnGestionProveedoresNOBD.setText("Gestión de Proveedores no bd");
        btnGestionProveedoresNOBD.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnGestionProveedoresNOBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionProveedoresNOBDActionPerformed(evt);
            }
        });

        btnGestionColab.setText("Gestión de Productos");
        btnGestionColab.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnGestionColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionColabActionPerformed(evt);
            }
        });

        btnPlanillas.setText("Planillas");
        btnPlanillas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnPlanillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanillasActionPerformed(evt);
            }
        });

        btnGetionProveedorSIBD.setText("pruebaproveedor si bd");
        btnGetionProveedorSIBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetionProveedorSIBDActionPerformed(evt);
            }
        });

        btnBD.setText("ClientesBD");
        btnBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBDActionPerformed(evt);
            }
        });

        mnuMenu.setText("Menú");

        mnuItemGesColab.setText("Gestión de Colaboradores");
        mnuItemGesColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemGesColabActionPerformed(evt);
            }
        });
        mnuMenu.add(mnuItemGesColab);

        mnuItemGesPuestos.setText("Gestión de Puestos");
        mnuItemGesPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemGesPuestosActionPerformed(evt);
            }
        });
        mnuMenu.add(mnuItemGesPuestos);

        mnuPlanilla.setText("Planillas");
        mnuPlanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPlanillaActionPerformed(evt);
            }
        });
        mnuMenu.add(mnuPlanilla);

        mnuMenuBar.add(mnuMenu);

        setJMenuBar(mnuMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGestionProveedoresNOBD, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGestionColab, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPlanillas, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(btnGetionProveedorSIBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestionColab, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlanillas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGestionProveedoresNOBD, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetionProveedorSIBD, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBD, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionColabActionPerformed
        ProductosView winColaborador = new ProductosView(this, false, listaC, listaPuestos);
        winColaborador.setVisible(true);
        //Lo que hace es que los datos del JDialog los devuelve 
        this.listaC = winColaborador.lista;
    }//GEN-LAST:event_btnGestionColabActionPerformed

    private void btnGestionProveedoresNOBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionProveedoresNOBDActionPerformed
        ProveedoresView winPuestos = new ProveedoresView(this, false, listaPuestos);
        winPuestos.setVisible(true);
        //Lo que hace es que los datos del JDialog los devuelve 
        this.listaPuestos = winPuestos.lista;
    }//GEN-LAST:event_btnGestionProveedoresNOBDActionPerformed

    private void btnPlanillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanillasActionPerformed
        VentasView winPlanilla = new VentasView(this, false, listaPlanilla, listaCliente, listaPuestos, listaPColab, listaPluses, listaC);
        winPlanilla.setVisible(true);
        //Lo que hace es que los datos del JDialog los devuelve 
        this.listaPlanilla = winPlanilla.listaPlanilla;
    }//GEN-LAST:event_btnPlanillasActionPerformed

    private void mnuItemGesColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemGesColabActionPerformed
        ProductosView winColaborador = new ProductosView(this, false, listaC, listaPuestos);
        winColaborador.setVisible(true);
        //Lo que hace es que los datos del JDialog los devuelve 
        this.listaC = winColaborador.lista;
    }//GEN-LAST:event_mnuItemGesColabActionPerformed

    private void mnuItemGesPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemGesPuestosActionPerformed
        ProveedoresView winPuestos = new ProveedoresView(this, false, listaPuestos);
        winPuestos.setVisible(true);
        //Lo que hace es que los datos del JDialog los devuelve 
        this.listaPuestos = winPuestos.lista;
    }//GEN-LAST:event_mnuItemGesPuestosActionPerformed

    private void mnuPlanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPlanillaActionPerformed
        VentasView winPlanilla = new VentasView(this, false, listaPlanilla, listaCliente, listaPuestos, listaPColab, listaPluses, listaC);
        winPlanilla.setVisible(true);
        //Lo que hace es que los datos del JDialog los devuelve 
        this.listaPlanilla = winPlanilla.listaPlanilla;
    }//GEN-LAST:event_mnuPlanillaActionPerformed

    private void btnGetionProveedorSIBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetionProveedorSIBDActionPerformed
        FrmProveedor view = new FrmProveedor(null, true);
        view.setVisible(true);

    }//GEN-LAST:event_btnGetionProveedorSIBDActionPerformed

    private void btnBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBDActionPerformed
        FrmCliente view = new FrmCliente(null, true);
        view.setVisible(true);
    }//GEN-LAST:event_btnBDActionPerformed
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource(
                        "img/recurso.png"));
        return retValue;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaniSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaniSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaniSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaniSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaniSys().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBD;
    private javax.swing.JButton btnGestionColab;
    private javax.swing.JButton btnGestionProveedoresNOBD;
    private javax.swing.JButton btnGetionProveedorSIBD;
    private javax.swing.JButton btnPlanillas;
    private javax.swing.JMenuItem mnuItemGesColab;
    private javax.swing.JMenuItem mnuItemGesPuestos;
    private javax.swing.JMenu mnuMenu;
    private javax.swing.JMenuBar mnuMenuBar;
    private javax.swing.JMenuItem mnuPlanilla;
    // End of variables declaration//GEN-END:variables
}
