/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import Modelo.Clientes.Cliente;
import clases.Productos;
import clases.Ventas;
import clases.Pluses;
import clases.PlusesColab;
import clases.Proveedor;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.property.TextAlignment;
import controlador.ClienteControlador;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vista.Cliente.FrmCliente;

/**
 *
 * @author Cristian y Reyman
 */
public class VentasView extends javax.swing.JDialog {

    // Objetos y Array List de otras clases. 
    Ventas ventas;
    Productos productos;
    Cliente cliente;
    Proveedor puestos;
    PlusesColab plusesColab;
    ArrayList<Cliente> listaCliente;
    MostrarPlanillaView mostrar;
    ArrayList<Ventas> listaPlanilla;
    ArrayList<PlusesColab> listaPColab;
    ArrayList<Pluses> listaPluses;
    ArrayList<Productos> listaC;
    ArrayList<Proveedor> listaPuesto;
    ClienteControlador clienteController;
    private FrmCliente vista;
    DefaultTableModel model;

    /**
     *
     * @param parent
     * @param modal
     * @param listaPlanilla lista de la planilla.
     * @param listaCliente
     * @param listaPuesto lista de los puestos.
     * @param listaPColab lista de la asignación de pluses al colaborador.
     * @param listaPluses lista de los pluses creados.
     * @param listaC lista de los colaboradores.
     */
    public VentasView(java.awt.Frame parent, boolean modal, ArrayList<Ventas> listaPlanilla, ArrayList<Cliente> listaCliente, ArrayList<Proveedor> listaPuesto,
            ArrayList<PlusesColab> listaPColab, ArrayList<Pluses> listaPluses, ArrayList<Productos> listaC) {
        super(parent, modal);
        initComponents();
        this.listaPlanilla = listaPlanilla;
        this.listaCliente = listaCliente;
        this.listaPuesto = listaPuesto;
        this.listaPColab = listaPColab;
        this.listaPluses = listaPluses;
        this.listaC = listaC;
        vista = new FrmCliente();
        clienteController = new ClienteControlador(vista);

        setLocationRelativeTo(null);
    }

    /**
     *
     * @param parent
     * @param modal
     */
    public VentasView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGenerar = new javax.swing.JPanel();
        btnGenerar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnbucarProducto = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCantVendida = new javax.swing.JTextField();
        bntBuscarCliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtCedCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlRegistrosPlanilla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlanilla = new javax.swing.JTable();
        pnlFiltrar = new javax.swing.JPanel();
        lblFiltrar = new javax.swing.JLabel();
        lblColaborador = new javax.swing.JLabel();
        chkFiltColab = new javax.swing.JCheckBox();
        chkFiltMes = new javax.swing.JCheckBox();
        lblMes = new javax.swing.JLabel();
        chkAño = new javax.swing.JCheckBox();
        lblAño = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        lblCant = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        btnEliminarInforme = new javax.swing.JButton();
        btnPDFEspecifico = new javax.swing.JButton();
        btnPDFTodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Ventas ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        pnlGenerar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Generar Informe "));

        btnGenerar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGenerar.setText("Generar");
        btnGenerar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar Producto");

        btnbucarProducto.setText("Buscar");
        btnbucarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbucarProductoActionPerformed(evt);
            }
        });

        txtCodigo.setEditable(false);

        txtNombre.setEditable(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtPrecio.setEditable(false);

        jLabel2.setText("Código");

        jLabel3.setText("Nombre");

        jLabel4.setText("Precio");

        jLabel5.setText("Cantidad Vendida:");

        bntBuscarCliente.setText("Buscar");
        bntBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarClienteActionPerformed(evt);
            }
        });

        jLabel6.setText("Buscar Cliente:");

        txtNombreCliente.setEditable(false);

        txtCedCliente.setEditable(false);

        jLabel7.setText("Cédula");

        jLabel8.setText("Nombre:");

        javax.swing.GroupLayout pnlGenerarLayout = new javax.swing.GroupLayout(pnlGenerar);
        pnlGenerar.setLayout(pnlGenerarLayout);
        pnlGenerarLayout.setHorizontalGroup(
            pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGenerarLayout.createSequentialGroup()
                .addGroup(pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGenerarLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlGenerarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlGenerarLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantVendida))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlGenerarLayout.createSequentialGroup()
                                .addGroup(pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlGenerarLayout.createSequentialGroup()
                                        .addGroup(pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlGenerarLayout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)))
                                    .addComponent(txtCedCliente)
                                    .addGroup(pnlGenerarLayout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGenerarLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntBuscarCliente))
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlGenerarLayout.createSequentialGroup()
                                .addGroup(pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlGenerarLayout.createSequentialGroup()
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnbucarProducto))
                                    .addComponent(jLabel4))
                                .addGap(0, 2, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnlGenerarLayout.setVerticalGroup(
            pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGenerarLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bntBuscarCliente)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtCedCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbucarProducto))
                .addGap(18, 18, 18)
                .addGroup(pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCantVendida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlRegistrosPlanilla.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Todos los registros de planillas "));

        tblPlanilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPlanilla);

        javax.swing.GroupLayout pnlRegistrosPlanillaLayout = new javax.swing.GroupLayout(pnlRegistrosPlanilla);
        pnlRegistrosPlanilla.setLayout(pnlRegistrosPlanillaLayout);
        pnlRegistrosPlanillaLayout.setHorizontalGroup(
            pnlRegistrosPlanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        pnlRegistrosPlanillaLayout.setVerticalGroup(
            pnlRegistrosPlanillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrosPlanillaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        lblFiltrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFiltrar.setText("Filtrar por:");

        lblColaborador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblColaborador.setText("Colaborador:");

        lblMes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMes.setText("Mes: ");

        lblAño.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAño.setText("Año:");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlFiltrarLayout = new javax.swing.GroupLayout(pnlFiltrar);
        pnlFiltrar.setLayout(pnlFiltrarLayout);
        pnlFiltrarLayout.setHorizontalGroup(
            pnlFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFiltrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkFiltColab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblColaborador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkFiltMes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkAño)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAño)
                .addGap(12, 12, 12)
                .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlFiltrarLayout.setVerticalGroup(
            pnlFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFiltrarLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(pnlFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkFiltColab)
                    .addGroup(pnlFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblColaborador, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblFiltrar))
                    .addGroup(pnlFiltrarLayout.createSequentialGroup()
                        .addGroup(pnlFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMes)
                                .addComponent(lblAño)
                                .addComponent(chkAño, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(1, 1, 1))
                    .addComponent(chkFiltMes))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        lblCant.setText("Cantidad de Registros:");

        txtCant.setEditable(false);

        btnEliminarInforme.setText("Eliminar");
        btnEliminarInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarInformeActionPerformed(evt);
            }
        });

        btnPDFEspecifico.setText("Generar PDF específico");

        btnPDFTodo.setText("Generar PDF de todo el informe");
        btnPDFTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblCant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnEliminarInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPDFEspecifico))
                            .addComponent(btnPDFTodo, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(pnlRegistrosPlanilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(pnlGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminarInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPDFEspecifico, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(btnPDFTodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 15, Short.MAX_VALUE)
                .addComponent(pnlRegistrosPlanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCant)
                    .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (!listaPlanilla.isEmpty()) {
            btnPDFTodo.setVisible(true);
            btnPDFEspecifico.setVisible(true);
        }
        PDFVision();
        mostrarTabla();

    }//GEN-LAST:event_formWindowActivated

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        if (txtCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecciona un producto para realizar el informe", "Error", JOptionPane.ERROR_MESSAGE);
        }

        if (txtCedCliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecciona un cliente para realizar el informe", "Error", JOptionPane.ERROR_MESSAGE);
        }

        if (txtCantVendida.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar la cantidad vendida", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Convertir la cantidad vendida a entero
            int cantidadVendida = Integer.parseInt(txtCantVendida.getText());

            // Buscar el producto original en la lista de productos
            Productos productoOriginal = null;
            for (Productos p : listaC) {
                if (p.getCodigo() == Integer.parseInt(txtCodigo.getText())) {
                    productoOriginal = p;
                    break;
                }
            }

            // Validar que haya suficiente stock
            if (cantidadVendida > productoOriginal.getCantDisponible()) {
                JOptionPane.showMessageDialog(null,
                        "No hay suficiente stock. \nStock disponible: " + productoOriginal.getCantDisponible(),
                        "Stock Insuficiente",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Restar la cantidad vendida del stock original
            productoOriginal.setCantDisponible(productoOriginal.getCantDisponible() - cantidadVendida);

            // Crear un nuevo registro de planilla
            Ventas planilla = new Ventas();
            planilla.setCedulaEmpleado(Integer.parseInt(txtCedCliente.getText()));
            planilla.setNomEmpleado(txtNombreCliente.getText());
            planilla.setCodigoProducto(Integer.parseInt(txtCodigo.getText()));
            planilla.setNombreProducto(txtNombre.getText());
            planilla.setPrecioProducto(Integer.parseInt(txtPrecio.getText()));
            planilla.setCantVendidos(cantidadVendida);

            // Agregar a la lista de planilla
            listaPlanilla.add(planilla);

            // Actualizar la tabla
            mostrarTabla();

            // Limpiar campos
            txtCodigo.setText("");
            txtNombre.setText("");
            txtPrecio.setText("");
            txtCantVendida.setText("");
            txtCedCliente.setText("");
            txtNombreCliente.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "La cantidad vendida debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
        }

        btnPDFTodo.setVisible(true);
        btnPDFEspecifico.setVisible(true);
    }//GEN-LAST:event_btnGenerarActionPerformed

    /**
     * Obtiene el salario de un empleado según su puesto.
     *
     * @param idPuesto El ID del puesto del empleado.
     * @return El salario correspondiente al puesto, o 0 si no se encuentra el
     * puesto.
     */
    public float getSalarioEmpleado(int idPuesto) {
        for (int i = 0; i < listaPuesto.size(); i++) {
            puestos = listaPuesto.get(i);
            if (idPuesto == puestos.getIdPuesto()) {
                return puestos.getIdPuesto();

            }
        }
        return 0;
    }

    /**
     * Busca en la tabla de planillas según los filtros seleccionados.
     *
     * @param evt El evento de buscar por teclado.
     */

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
//        String titulos[] = {"Id Ventas", "Fecha Creación", "Mes a Pagar", "Fecha Pago", "Ced Empleado", "Empleado",
//            "Sal Base", "Total x Pluses", "Salario Bruto", "Deducc CCSS", "Deducción BP", "Salario Neto"};
//        model = new DefaultTableModel(null, titulos);
//
//        if (chkFiltColab.isSelected()) {
//            String textoBuscar = txtBuscar.getText();
//            int cedulaEmpleado = 0;
//            try {
//                cedulaEmpleado = Integer.parseInt(textoBuscar);
//            } catch (NumberFormatException e) {
//                JOptionPane.showMessageDialog(this, "El texto ingresado no es un número entero");
//                return;
//            }
//
//            for (int i = 0; i < listaPlanilla.size(); i++) {
//                planilla = listaPlanilla.get(i);
//                if (planilla.getCedulaEmpleado() == cedulaEmpleado) {
//                    Object nuevaFila[] = {planilla.getIdPlanilla(), planilla.getFechaRecibo(), planilla.getMesPuesto(),
//                        planilla.getFechaPago(), planilla.getCedulaEmpleado(), planilla.getNomEmpleado(),
//                        planilla.getSalBase(), planilla.getTotalPluses(), planilla.getSalBruto(),
//                        calcularSalarioBruto(), calcularDeduccionCCSS(),
//                        calcularDeduccionBP(), calcularSalarioNeto()};
//                    model.addRow(nuevaFila);
//                }
//            }
//            tblPlanilla.setModel(model);
//
//            txtCant.setText(String.valueOf(model.getRowCount()));
//
//        } else if (chkFiltMes.isSelected()) {
//            for (int i = 0; i < listaPlanilla.size(); i++) {
//                planilla = listaPlanilla.get(i);
//
//                if (planilla.getMesPuesto().equals(String.valueOf(txtBuscar.getText()))) {
//                    Object nuevaFila[] = {planilla.getIdPlanilla(), planilla.getFechaRecibo(), planilla.getMesPuesto(),
//                        planilla.getFechaPago(), planilla.getCedulaEmpleado(), planilla.getNomEmpleado(), planilla.getSalBase(),
//                        planilla.getTotalPluses(), planilla.getSalBruto(), planilla.getDeducCCSS(), planilla.getDeducBP(), planilla.getSalNeto()};
//                    model.addRow(nuevaFila);
//                }
//            }
//            tblPlanilla.setModel(model);
//
//            txtCant.setText(String.valueOf(model.getRowCount()));
//        } else if (chkAño.isSelected()) {
//            for (int i = 0; i < listaPlanilla.size(); i++) {
//                planilla = listaPlanilla.get(i);
//                if (planilla.getFechaPago().substring(6, 10).equals(txtBuscar.getText())) {
//                    Object nuevaFila[] = {planilla.getIdPlanilla(), planilla.getFechaRecibo(), planilla.getMesPuesto(),
//                        planilla.getFechaPago(), planilla.getCedulaEmpleado(), planilla.getNomEmpleado(), planilla.getSalBase(),
//                        planilla.getTotalPluses(), planilla.getSalBruto(), planilla.getDeducCCSS(), planilla.getDeducBP(), planilla.getSalNeto()};
//                    model.addRow(nuevaFila);
//                }
//            }
//            tblPlanilla.setModel(model);
//
//            txtCant.setText(String.valueOf(model.getRowCount()));
//        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnbucarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbucarProductoActionPerformed
       ProductosBuscaView view = new ProductosBuscaView(null, true, listaC);
        view.setVisible(true);

        // Obtener el producto seleccionado
        Productos productoSeleccionado = view.getProductoSeleccionado();

        if (productoSeleccionado != null) {
            // Setear los valores en los campos de texto
            txtCodigo.setText(String.valueOf(productoSeleccionado.getCodigo()));
            txtNombre.setText(productoSeleccionado.getNombre());
            txtPrecio.setText(String.valueOf(productoSeleccionado.getPrecio()));
        }
    }//GEN-LAST:event_btnbucarProductoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnEliminarInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarInformeActionPerformed
        // Verificar si hay registros en la tabla
        if (listaPlanilla.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay registros para eliminar", "Lista Vacía", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

// Obtener la fila seleccionada
        int filaSeleccionada = tblPlanilla.getSelectedRow();

// Verificar si se ha seleccionado una fila
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro para eliminar", "Selección Requerida", JOptionPane.WARNING_MESSAGE);
            return;
        }

// Preguntar al usuario si realmente desea eliminar el registro seleccionado
        int respuesta = JOptionPane.showConfirmDialog(null,
                "¿Está seguro que desea eliminar el registro seleccionado?",
                "Confirmar Eliminación",
                JOptionPane.YES_NO_OPTION);

// Si el usuario confirma (respuesta == 0 significa que seleccionó "Sí")
        if (respuesta == 0) {
            // Eliminar el registro de la lista
            listaPlanilla.remove(filaSeleccionada);

            // Actualizar la tabla
            mostrarTabla();

            // Mostrar mensaje de confirmación
            JOptionPane.showMessageDialog(null, "El registro seleccionado ha sido eliminado", "Registro Eliminado", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarInformeActionPerformed

    private void btnPDFTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFTodoActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblPlanilla.getModel();

        // Verifica si hay filas visibles
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No hay datos para exportar al PDF.");
            return;
        }

        // Ruta del PDF (escritorio)
        String rutaEscritorio = System.getProperty("user.home") + "/Desktop/";
        String nombreArchivo = "Informe_VentasCompleto_" + LocalDate.now() + ".pdf";
        String rutaCompleta = rutaEscritorio + nombreArchivo.replaceAll("[^a-zA-Z0-9._-]", "_");

        try {
            // Crear el PDF
            PdfWriter writer = new PdfWriter(rutaCompleta);
            PdfDocument pdf = new PdfDocument(writer);
            Document document = new Document(pdf);

            // Agregar título
            document.add(new Paragraph("Informe de Ventas")
                    .setBold()
                    .setFontSize(16)
                    .setMarginBottom(10));
            document.add(new Paragraph("Todas las ventas registradas")
                    .setFontSize(12)
                    .setMarginBottom(20));

            // Crear tabla en el PDF
            int columnCount = model.getColumnCount();
            float totalWidth = 520f; // Ancho total de la tabla en puntos
            float[] columnWidths = new float[columnCount];
            float defaultWidth = totalWidth / columnCount;

            for (int i = 0; i < columnCount; i++) {
                columnWidths[i] = Math.max(defaultWidth, model.getColumnName(i).length() * 6f); // Ajuste basado en texto
            }

            Table pdfTable = new Table(columnWidths);
            pdfTable.setWidth(totalWidth);

            // Agregar encabezados al PDF
            for (int i = 0; i < columnCount; i++) {
                Cell headerCell = new Cell().add(new Paragraph(model.getColumnName(i)))
                        .setBold()
                        .setTextAlignment(TextAlignment.CENTER)
                        .setBackgroundColor(ColorConstants.LIGHT_GRAY);
                pdfTable.addHeaderCell(headerCell);
            }

            // Agregar datos visibles de la tabla
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < columnCount; j++) {
                    String cellData = model.getValueAt(i, j) == null ? "" : model.getValueAt(i, j).toString();
                    Cell cell = new Cell().add(new Paragraph(cellData)
                            .setTextAlignment(TextAlignment.LEFT)
                            .setFontSize(10));
                    pdfTable.addCell(cell);
                }
            }

            // Agregar la tabla al documento
            document.add(pdfTable);

            // Cerrar documento
            document.close();

            // Confirmar éxito
            JOptionPane.showMessageDialog(this, "PDF generado exitosamente en: " + rutaCompleta);

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al generar el PDF: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPDFTodoActionPerformed

    private void bntBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarClienteActionPerformed
        // Crear la vista de búsqueda
        ClienteBuscaView view = new ClienteBuscaView(null, true);

        // Mostrar la vista
        view.setVisible(true);

        // Obtener el cliente seleccionado
        Cliente clienteSeleccionado = view.getClienteSeleccionado();

        if (clienteSeleccionado != null) {
            // Setear los valores en los campos de texto
            txtCedCliente.setText(clienteSeleccionado.getCedula());
            txtNombreCliente.setText(clienteSeleccionado.getNombreCompleto());

//            // Ahora, cuando se cree el objeto planilla, se puede usar:
//            planilla.setCedulaEmpleado(Integer.parseInt(txtCedCliente.getText()));
//            planilla.setNomEmpleado(txtNombreCliente.getText());
        }
       
    }//GEN-LAST:event_bntBuscarClienteActionPerformed

    public void mostrarTabla() {

        String titulos[] = {"Id Planilla", "Fecha Creación", "Cedula Cliente", "Cliente", "Código Producto", "producto",
            "Precio de Unidad", "CantVendida", "Subtotal", "Impuestos", "Total"};
        model = new DefaultTableModel(null, titulos);
        // Obtener el tamaño mínimo entre las listas

        for (int i = 0; i < listaPlanilla.size(); i++) {
            ventas = listaPlanilla.get(i);
            Object nuevaFila[] = {
                ventas.getIdPlanilla(), ventas.getFechaRecibo(), ventas.getCedulaEmpleado(), ventas.getNomEmpleado(),
                ventas.getCodigoProducto(), ventas.getNombreProducto(), ventas.getPrecioProducto(), ventas.getCantVendidos(),
                calcularSubTotal(), calcularImpuestos(), calcularTotal()};
            model.addRow(nuevaFila);

        }
        tblPlanilla.setModel(model);

        // Actualizar el contador de filas    
        txtCant.setText(String.valueOf(model.getRowCount()));
    }

    public int calcularSubTotal() {
        int precioOriginal = ventas.getPrecioProducto();
        int cantidadVendida = ventas.getCantVendidos();
        int resultado = precioOriginal * cantidadVendida;
        return resultado;
    }

    public int calcularImpuestos() {
        int impuestos = (int) (0.13 * calcularSubTotal());
        return impuestos;
    }

    public int calcularTotal() {
        int total = calcularSubTotal() + calcularImpuestos();
        return total;
    }

    public void PDFVision() {
        btnPDFEspecifico.setVisible(false);
        btnPDFTodo.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentasView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentasView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentasView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentasView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentasView dialog = new VentasView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBuscarCliente;
    private javax.swing.JButton btnEliminarInforme;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnPDFEspecifico;
    private javax.swing.JButton btnPDFTodo;
    private javax.swing.JButton btnbucarProducto;
    private javax.swing.JCheckBox chkAño;
    private javax.swing.JCheckBox chkFiltColab;
    private javax.swing.JCheckBox chkFiltMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblCant;
    private javax.swing.JLabel lblColaborador;
    private javax.swing.JLabel lblFiltrar;
    private javax.swing.JLabel lblMes;
    private javax.swing.JPanel pnlFiltrar;
    private javax.swing.JPanel pnlGenerar;
    private javax.swing.JPanel pnlRegistrosPlanilla;
    private javax.swing.JTable tblPlanilla;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtCantVendida;
    private javax.swing.JTextField txtCedCliente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
